// 数式再現練習の組み込み問題集(難易度別・各100問)

export type Level = "beginner" | "intermediate" | "advanced";

export const LEVEL_LABELS: Record<Level, string> = {
  beginner: "初級",
  intermediate: "中級",
  advanced: "上級",
};

const r = String.raw;

export const PROBLEMS: Record<Level, string[]> = {
  // ---------- 初級: 単一の構文・記号を短く ----------
  beginner: [
    r`\frac{1}{2}`,
    r`x^2`,
    r`\sqrt{2}`,
    r`a_n`,
    r`\alpha`,
    r`2x + 3 = 7`,
    r`x \neq 0`,
    r`|x|`,
    r`x \to \infty`,
    r`y = \sin x`,
    r`\frac{2}{3}`,
    r`x^3 + 1`,
    r`\sqrt{x+1}`,
    r`x_i`,
    r`\beta + \gamma`,
    r`y = ax + b`,
    r`x \leq 5`,
    r`|a - b|`,
    r`n \to 0`,
    r`y = \cos x`,
    r`\frac{a}{b}`,
    r`a^m a^n = a^{m+n}`,
    r`\sqrt[3]{8} = 2`,
    r`a_{n+1}`,
    r`\Delta x`,
    r`y = x^2 + 2x + 1`,
    r`0 \leq p \leq 1`,
    r`\tan\theta`,
    r`f(x)`,
    r`\log x`,
    r`\frac{x}{y+1}`,
    r`(a^m)^n = a^{mn}`,
    r`\sqrt{a^2 + b^2}`,
    r`a_1, a_2, \dots, a_n`,
    r`\pi \approx 3.14`,
    r`(a+b)^2 = a^2 + 2ab + b^2`,
    r`a > b`,
    r`\sin 30^\circ = \frac{1}{2}`,
    r`f(x) = 2x + 1`,
    r`\ln e = 1`,
    r`\frac{1}{x^2}`,
    r`x^{-1} = \frac{1}{x}`,
    r`\sqrt{\frac{a}{b}}`,
    r`a_{ij}`,
    r`\theta = 45^\circ`,
    r`x^2 - y^2 = (x+y)(x-y)`,
    r`x \approx 1.41`,
    r`\log_2 8 = 3`,
    r`f: A \to B`,
    r`e^x`,
    r`\frac{x+1}{x-1}`,
    r`2^n`,
    r`\frac{1}{\sqrt{2}}`,
    r`a_n = 2n - 1`,
    r`\lambda x`,
    r`a = b = c`,
    r`x = \pm\sqrt{5}`,
    r`e^{-x}`,
    r`g(f(x))`,
    r`10^{-3}`,
    r`\frac{1}{2} + \frac{1}{3} = \frac{5}{6}`,
    r`n!`,
    r`\omega t`,
    r`x \in \mathbb{R}`,
    r`\pm 1`,
    r`5! = 120`,
    r`f'(x)`,
    r`\sigma^2`,
    r`n \in \mathbb{N}`,
    r`a \cdot b`,
    r`\frac{3}{4} \times \frac{2}{3} = \frac{1}{2}`,
    r`\frac{dy}{dx}`,
    r`A \cup B`,
    r`a \times b`,
    r`a : b = 2 : 3`,
    r`\bar{x}`,
    r`A \cap B`,
    r`a \div b`,
    r`S = \frac{1}{2}bh`,
    r`\hat{y}`,
    r`A \subset B`,
    r`90^\circ`,
    r`V = a^3`,
    r`\vec{v}`,
    r`\emptyset`,
    r`\angle ABC`,
    r`C = 2\pi r`,
    r`\dot{x}`,
    r`\frac{a}{b} = \frac{c}{d}`,
    r`\triangle ABC`,
    r`d = vt`,
    r`x'`,
    r`x^2 + y^2 = 1`,
    r`AB \parallel CD`,
    r`E = mc^2`,
    r`(x, y)`,
    r`x^2 + y^2 = r^2`,
    r`AB \perp CD`,
    r`F = ma`,
    r`v = v_0 + at`,
  ],

  // ---------- 中級: 複数構文の組み合わせ・定番公式 ----------
  intermediate: [
    r`\int_0^1 x^2 \, dx = \frac{1}{3}`,
    r`\sum_{k=1}^{n} k = \frac{n(n+1)}{2}`,
    r`\lim_{x \to 0} \frac{\sin x}{x} = 1`,
    r`e^{i\pi} + 1 = 0`,
    r`\binom{n}{k} = \frac{n!}{k!(n-k)!}`,
    r`x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`,
    r`\sin^2\theta + \cos^2\theta = 1`,
    r`\frac{\partial f}{\partial x}`,
    r`\vec{a} \cdot \vec{b} = |\vec{a}||\vec{b}|\cos\theta`,
    r`\log_a xy = \log_a x + \log_a y`,
    r`\int x \, dx = \frac{x^2}{2} + C`,
    r`\sum_{k=1}^{n} k^2 = \frac{n(n+1)(2n+1)}{6}`,
    r`\lim_{x \to \infty} \frac{1}{x} = 0`,
    r`e^{i\theta} = \cos\theta + i\sin\theta`,
    r`\binom{n}{0} = \binom{n}{n} = 1`,
    r`ax^2 + bx + c = 0`,
    r`\sin(\alpha + \beta) = \sin\alpha\cos\beta + \cos\alpha\sin\beta`,
    r`\frac{\partial^2 f}{\partial x^2}`,
    r`\vec{a} \times \vec{b}`,
    r`\log_a \frac{x}{y} = \log_a x - \log_a y`,
    r`\int_a^b f(x) \, dx`,
    r`\sum_{i=1}^{n} x_i`,
    r`\lim_{h \to 0} \frac{f(x+h) - f(x)}{h}`,
    r`z = a + bi`,
    r`P(A \cup B) = P(A) + P(B) - P(A \cap B)`,
    r`D = b^2 - 4ac`,
    r`\cos 2\theta = 1 - 2\sin^2\theta`,
    r`\frac{d}{dx} e^x = e^x`,
    r`|\vec{a}| = \sqrt{a_1^2 + a_2^2}`,
    r`\log_a x^n = n \log_a x`,
    r`\int_0^\pi \sin x \, dx = 2`,
    r`\sum_{n=1}^{\infty} \frac{1}{2^n} = 1`,
    r`\lim_{n \to \infty} a_n = \alpha`,
    r`|z| = \sqrt{a^2 + b^2}`,
    r`P(A \mid B) = \frac{P(A \cap B)}{P(B)}`,
    r`\tan\theta = \frac{\sin\theta}{\cos\theta}`,
    r`\frac{d}{dx} \ln x = \frac{1}{x}`,
    r`\overrightarrow{AB}`,
    r`\log_a b = \frac{\log_c b}{\log_c a}`,
    r`\int_1^e \frac{1}{x} \, dx = 1`,
    r`\prod_{k=1}^{n} k = n!`,
    r`\left( 1 + \frac{1}{n} \right)^n`,
    r`\bar{z} = a - bi`,
    r`E[X] = \sum_i x_i p_i`,
    r`(fg)' = f'g + fg'`,
    r`a_n = a_1 + (n-1)d`,
    r`\nabla f`,
    r`i^2 = -1`,
    r`V[X] = E[X^2] - (E[X])^2`,
    r`\left( \frac{f}{g} \right)' = \frac{f'g - fg'}{g^2}`,
    r`a_n = a_1 r^{n-1}`,
    r`\Delta y = f(x + \Delta x) - f(x)`,
    r`\arg z = \theta`,
    r`\sqrt{x^2} = |x|`,
    r`S_n = \frac{a_1 (1 - r^n)}{1 - r}`,
    r`y'' + y = 0`,
    r`\sinh x = \frac{e^x - e^{-x}}{2}`,
    r`|x - a| < \delta`,
    r`\sum_{n=0}^{\infty} ar^n = \frac{a}{1-r}`,
    r`\frac{dv}{dt} = a`,
    r`\cosh^2 x - \sinh^2 x = 1`,
    r`\forall x \in \mathbb{R}`,
    r`f^{-1}(x)`,
    r`s = \int_0^t v \, dt`,
    r`\arcsin x`,
    r`\exists x > 0`,
    r`(f \circ g)(x) = f(g(x))`,
    r`W = \int F \, dx`,
    r`\tan^{-1} x`,
    r`\mathbb{N} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R}`,
    r`\max_{x \in [0,1]} f(x)`,
    r`PV = nRT`,
    r`\frac{180^\circ}{\pi}`,
    r`A \subseteq B`,
    r`\min\{a, b\}`,
    r`v = f\lambda`,
    r`\ell = r\theta`,
    r`\gcd(a, b)`,
    r`T = 2\pi\sqrt{\frac{l}{g}}`,
    r`S = \frac{1}{2} r^2 \theta`,
    r`a \equiv b \pmod{n}`,
    r`E = \frac{1}{2}mv^2`,
    r`\sin\theta \approx \theta`,
    r`\frac{1}{1 + \frac{1}{x}}`,
    r`p = mv`,
    r`x_{1,2} = 1 \pm \sqrt{2}`,
    r`\frac{\sqrt{a} + \sqrt{b}}{2}`,
    r`F = G\frac{m_1 m_2}{r^2}`,
    r`\overline{AB}`,
    r`x^{2/3}`,
    r`V = IR`,
    r`\binom{n+1}{k} = \binom{n}{k} + \binom{n}{k-1}`,
    r`a^{1/2} = \sqrt{a}`,
    r`P = IV`,
    r`\sum_{k=0}^{n} \binom{n}{k} = 2^n`,
    r`\frac{n(n-1)}{2}`,
    r`Q = mc\Delta T`,
    r`(a+b)^n = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k`,
    r`\sqrt{2} \approx 1.414`,
    r`\int_0^1 \sqrt{x} \, dx = \frac{2}{3}`,
  ],

  // ---------- 上級: 行列・重積分・有名定理・物理/統計 ----------
  advanced: [
    r`\begin{pmatrix} a & b \\ c & d \end{pmatrix}`,
    r`\int_{-\infty}^{\infty} e^{-x^2} \, dx = \sqrt{\pi}`,
    r`f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!}(x-a)^n`,
    r`i\hbar \frac{\partial}{\partial t} \Psi = \hat{H} \Psi`,
    r`\frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}`,
    r`\begin{cases} x + y = 1 \\ x - y = 3 \end{cases}`,
    r`\nabla \times \vec{E} = -\frac{\partial \vec{B}}{\partial t}`,
    r`\det(A - \lambda I) = 0`,
    r`\lim_{n\to\infty} \left( 1 + \frac{1}{n} \right)^n = e`,
    r`\oint_C \vec{F} \cdot d\vec{r} = \iint_S (\nabla \times \vec{F}) \cdot d\vec{S}`,
    r`\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}`,
    r`\iint_D f(x,y) \, dx \, dy`,
    r`e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!}`,
    r`E = \hbar\omega`,
    r`P(B \mid A) = \frac{P(A \mid B) P(B)}{P(A)}`,
    r`f(x) = \begin{cases} x^2 & x \geq 0 \\ -x & x < 0 \end{cases}`,
    r`\nabla \cdot \vec{E} = \frac{\rho}{\varepsilon_0}`,
    r`A\vec{x} = \lambda\vec{x}`,
    r`\lim_{n \to \infty} \frac{1}{n} \sum_{k=1}^n f\left( \frac{k}{n} \right) = \int_0^1 f(x) \, dx`,
    r`\int_a^b f'(x) \, dx = f(b) - f(a)`,
    r`\begin{bmatrix} x \\ y \end{bmatrix}`,
    r`\iiint_V \rho \, dV`,
    r`\sin x = x - \frac{x^3}{3!} + \frac{x^5}{5!} - \cdots`,
    r`\Delta x \Delta p \geq \frac{\hbar}{2}`,
    r`\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^n (x_i - \bar{x})^2}`,
    r`\begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc`,
    r`\nabla \cdot \vec{B} = 0`,
    r`A^T A = I`,
    r`\frac{d}{dx} \int_a^x f(t) \, dt = f(x)`,
    r`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`,
    r`A^{-1} = \frac{1}{ad-bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}`,
    r`\oint_C \vec{F} \cdot d\vec{r}`,
    r`\ln(1+x) = \sum_{n=1}^{\infty} \frac{(-1)^{n-1}}{n} x^n`,
    r`\nabla \times \vec{B} = \mu_0 \vec{J} + \mu_0 \varepsilon_0 \frac{\partial \vec{E}}{\partial t}`,
    r`P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}`,
    r`\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix}`,
    r`\int_0^{2\pi} \int_0^R r \, dr \, d\theta = \pi R^2`,
    r`\zeta(s) = \sum_{n=1}^{\infty} \frac{1}{n^s}`,
    r`\nabla^2 \phi = 0`,
    r`\chi^2 = \sum \frac{(O - E)^2}{E}`,
    r`\mathrm{tr}(A) = \sum_i a_{ii}`,
    r`\int u \, dv = uv - \int v \, du`,
    r`\zeta(2) = \frac{\pi^2}{6}`,
    r`\frac{\partial u}{\partial t} = k \frac{\partial^2 u}{\partial x^2}`,
    r`H(X) = -\sum_i p_i \log_2 p_i`,
    r`\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}`,
    r`\mathcal{L}\{f(t)\} = \int_0^\infty e^{-st} f(t) \, dt`,
    r`\Gamma(n) = (n-1)!`,
    r`\frac{\partial^2 u}{\partial t^2} = c^2 \nabla^2 u`,
    r`\hat{\beta} = (X^T X)^{-1} X^T y`,
    r`U^n = \begin{pmatrix} 1 & n \\ 0 & 1 \end{pmatrix}`,
    r`\hat{f}(\xi) = \int_{-\infty}^{\infty} f(x) e^{-2\pi i x \xi} \, dx`,
    r`\Gamma(z) = \int_0^\infty t^{z-1} e^{-t} \, dt`,
    r`E^2 = (mc^2)^2 + (pc)^2`,
    r`r = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum (x_i - \bar{x})^2 \sum (y_i - \bar{y})^2}}`,
    r`\frac{\partial^2 f}{\partial x \partial y} = \frac{\partial^2 f}{\partial y \partial x}`,
    r`f(x) = \frac{a_0}{2} + \sum_{n=1}^{\infty} \left( a_n \cos nx + b_n \sin nx \right)`,
    r`\pi = 4 \sum_{n=0}^{\infty} \frac{(-1)^n}{2n+1}`,
    r`ds^2 = -c^2 dt^2 + dx^2`,
    r`\Phi(x) = \int_{-\infty}^x \frac{1}{\sqrt{2\pi}} e^{-t^2/2} \, dt`,
    r`df = \frac{\partial f}{\partial x} dx + \frac{\partial f}{\partial y} dy`,
    r`x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}`,
    r`e = \sum_{n=0}^{\infty} \frac{1}{n!}`,
    r`F = \frac{1}{4\pi\varepsilon_0} \frac{q_1 q_2}{r^2}`,
    r`\left( \sum a_i b_i \right)^2 \leq \left( \sum a_i^2 \right)\left( \sum b_i^2 \right)`,
    r`\nabla f = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y} \right)`,
    r`F_n = F_{n-1} + F_{n-2}`,
    r`\sum_{n=1}^{\infty} \frac{(-1)^{n+1}}{n} = \ln 2`,
    r`R_{\mu\nu} - \frac{1}{2} R g_{\mu\nu} = \frac{8\pi G}{c^4} T_{\mu\nu}`,
    r`\frac{a+b}{2} \geq \sqrt{ab}`,
    r`J = \begin{pmatrix} \frac{\partial x}{\partial u} & \frac{\partial x}{\partial v} \\ \frac{\partial y}{\partial u} & \frac{\partial y}{\partial v} \end{pmatrix}`,
    r`\cos z = \frac{e^{iz} + e^{-iz}}{2}`,
    r`m\ddot{x} + c\dot{x} + kx = 0`,
    r`|x + y| \leq |x| + |y|`,
    r`\oint_\gamma \frac{dz}{z} = 2\pi i`,
    r`\frac{Dv}{Dt} = \frac{\partial v}{\partial t} + (v \cdot \nabla) v`,
    r`\ddot{\theta} + \frac{g}{l} \sin\theta = 0`,
    r`\| \vec{x} \|_2 = \sqrt{\sum_i x_i^2}`,
    r`f(a) = \frac{1}{2\pi i} \oint_\gamma \frac{f(z)}{z - a} \, dz`,
    r`\frac{dy}{dx} + P(x) y = Q(x)`,
    r`\lim_{n\to\infty} \frac{F_{n+1}}{F_n} = \frac{1+\sqrt{5}}{2}`,
    r`\langle \vec{u}, \vec{v} \rangle = 0`,
    r`\int_0^\infty \frac{\sin x}{x} \, dx = \frac{\pi}{2}`,
    r`a_{n+1} = \frac{1}{2}\left( a_n + \frac{2}{a_n} \right)`,
    r`e^{A} = \sum_{k=0}^{\infty} \frac{A^k}{k!}`,
    r`\lim_{x \to 0^+} x \ln x = 0`,
    r`a^p \equiv a \pmod{p}`,
    r`\int_{-1}^{1} \frac{dx}{\sqrt{1 - x^2}} = \pi`,
    r`x^n + y^n = z^n`,
    r`\pi(x) \sim \frac{x}{\ln x}`,
    r`\left| \int f \right| \leq \int |f|`,
    r`\sum_{d \mid n} \varphi(d) = n`,
    r`\int_0^1 \frac{\ln x}{x - 1} \, dx = \frac{\pi^2}{6}`,
    r`y = e^{\lambda x}`,
    r`\sqrt{2} = 1 + \cfrac{1}{2 + \cfrac{1}{2 + \cdots}}`,
    r`\frac{1 + \sqrt{5}}{2}`,
    r`\begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}`,
    r`\lim_{x\to\infty} \left(1 + \frac{a}{x}\right)^x = e^a`,
    r`\mathrm{Res}_{z=a} f(z)`,
    r`\prod_{p} \frac{1}{1 - p^{-s}}`,
  ],
};
